version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db           # Синхронизируем папку db
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1